//CÁLCULO DO IMC
//FÓRMULA PESO DIVIDIDO PELA ALTURA AO QUADRADO
peso = prompt("Digite o seu peso (kg):")
altura = prompt("Digite a sua altura (m):")
imc = peso / (altura * altura)
document.write("Cálculo do IMC.")
document.write("<br>")
document.write("<br>Com " +peso+ " kg e " +altura+ " m. Seu IMC é: " +imc.toFixed(2)+".")
document.write("<br>")
document.write("<br>Abaixo de 17 				Muito abaixo do peso.")
document.write("<br>Entre 17 e 18,49    Abaixo do peso.")
document.write("<br>Entre 18,5 e 24,99  Peso normal.")
document.write("<br>Entre 25 e 29,99    Acima do peso.")
document.write("<br>Entre 30 e 34,99    Obesidade I.")
document.write("<br>Entre 35 e 39,99    Obesidade II.")